# Generated by Django 5.0.6 on 2026-09-25 01:23

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('icono', models.CharField(default='fa-solid fa-layer-group', max_length=60)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('activa', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'categoría',
                'verbose_name_plural': 'categorías',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='EstadoSolicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.SlugField(max_length=30, unique=True)),
                ('nombre', models.CharField(max_length=60)),
                ('descripcion', models.CharField(blank=True, max_length=200)),
                ('orden', models.PositiveSmallIntegerField(default=0)),
                ('color', models.CharField(default='azul', max_length=20)),
                ('es_final', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'estado de solicitud',
                'verbose_name_plural': 'estados de solicitud',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='RequerimientoWeb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_negocio', models.CharField(max_length=150)),
                ('rubro', models.CharField(max_length=60)),
                ('descripcion_negocio', models.TextField()),
                ('publico_objetivo', models.CharField(blank=True, max_length=200)),
                ('tipo_sitio', models.CharField(choices=[('landing', 'Landing page'), ('corporativo', 'Sitio corporativo o institucional'), ('portafolio', 'Portafolio o blog'), ('servicios', 'Sitio de servicios con reservas'), ('tienda', 'Tienda online')], max_length=20)),
                ('tiene_sitio_actual', models.BooleanField(default=False)),
                ('url_sitio_actual', models.URLField(blank=True)),
                ('objetivos', models.JSONField(blank=True, default=list)),
                ('num_paginas', models.PositiveSmallIntegerField(default=5)),
                ('complejidad', models.CharField(choices=[('basica', 'Básica'), ('media', 'Media'), ('alta', 'Alta')], default='media', max_length=10)),
                ('funcionalidades', models.JSONField(blank=True, default=list)),
                ('integraciones', models.JSONField(blank=True, default=list)),
                ('tiene_contenido', models.BooleanField(default=False)),
                ('observaciones', models.TextField(blank=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'requerimiento web',
                'verbose_name_plural': 'requerimientos web',
            },
        ),
        migrations.CreateModel(
            name='CodigoVerificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_hash', models.CharField(max_length=128)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('expira', models.DateTimeField()),
                ('intentos', models.PositiveSmallIntegerField(default=0)),
                ('usado', models.BooleanField(default=False)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='codigos_verificacion', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'código de verificación',
                'verbose_name_plural': 'códigos de verificación',
                'ordering': ['-creado'],
            },
        ),
        migrations.CreateModel(
            name='MensajeAsistente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sesion', models.CharField(db_index=True, max_length=64)),
                ('contenido', models.TextField()),
                ('es_asistente', models.BooleanField(default=False)),
                ('intencion', models.CharField(blank=True, max_length=40)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mensajes_asistente', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'mensaje del asistente',
                'verbose_name_plural': 'mensajes del asistente',
                'ordering': ['fecha', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='PerfilCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.CharField(blank=True, max_length=200, verbose_name='empresa o emprendimiento')),
                ('telefono', models.CharField(blank=True, max_length=20, verbose_name='teléfono')),
                ('rut', models.CharField(blank=True, max_length=12, verbose_name='RUT')),
                ('ciudad', models.CharField(blank=True, max_length=100)),
                ('recibir_notificaciones', models.BooleanField(default=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_cliente', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'perfil de cliente',
                'verbose_name_plural': 'perfiles de cliente',
            },
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('slug', models.SlugField(blank=True, max_length=140, unique=True)),
                ('resumen', models.CharField(max_length=180)),
                ('descripcion', models.TextField()),
                ('incluye', models.TextField(blank=True, help_text='Un elemento por línea.')),
                ('tipo', models.CharField(choices=[('Creacion', 'Creación de página web'), ('Mejora', 'Mejora de página existente'), ('Soporte', 'Soporte técnico'), ('Mantenimiento', 'Mantenimiento')], max_length=20)),
                ('precio_base', models.PositiveIntegerField(default=0, help_text='Valor referencial en CLP. Use 0 para "a cotizar".')),
                ('plazo_referencial', models.CharField(blank=True, max_length=60)),
                ('destacado', models.BooleanField(default=False)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='servicios', to='plataforma.categoria')),
            ],
            options={
                'verbose_name': 'servicio',
                'verbose_name_plural': 'servicios',
                'ordering': ['tipo', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(blank=True, editable=False, max_length=20, null=True, unique=True)),
                ('tipo', models.CharField(choices=[('Creacion', 'Creación de página web'), ('Mejora', 'Mejora de página existente'), ('Soporte', 'Soporte técnico'), ('Mantenimiento', 'Mantenimiento')], max_length=20)),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('url_sitio', models.URLField(blank=True, verbose_name='sitio web')),
                ('detalles', models.JSONField(blank=True, default=dict)),
                ('prioridad', models.CharField(choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta'), ('urgente', 'Urgente')], default='media', max_length=10)),
                ('fecha_deseada', models.DateField(blank=True, null=True, verbose_name='fecha deseada de entrega')),
                ('notas_internas', models.TextField(blank=True)),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes', to=settings.AUTH_USER_MODEL)),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitudes', to='plataforma.estadosolicitud')),
                ('requerimiento', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitud', to='plataforma.requerimientoweb')),
                ('servicio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes', to='plataforma.servicio')),
            ],
            options={
                'verbose_name': 'solicitud',
                'verbose_name_plural': 'solicitudes',
                'ordering': ['-fecha_solicitud'],
            },
        ),
        migrations.CreateModel(
            name='HistorialSolicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.TextField(blank=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('estado_anterior', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='plataforma.estadosolicitud')),
                ('estado_nuevo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='plataforma.estadosolicitud')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='plataforma.solicitud')),
            ],
            options={
                'verbose_name': 'historial de solicitud',
                'verbose_name_plural': 'historial de solicitudes',
                'ordering': ['-fecha', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='Estimacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.PositiveIntegerField()),
                ('monto_minimo', models.PositiveIntegerField()),
                ('monto_maximo', models.PositiveIntegerField()),
                ('factor_complejidad', models.DecimalField(decimal_places=2, default=1, max_digits=4)),
                ('desglose', models.JSONField(blank=True, default=list)),
                ('semanas_minimas', models.PositiveSmallIntegerField(default=1)),
                ('semanas_maximas', models.PositiveSmallIntegerField(default=2)),
                ('es_referencial', models.BooleanField(default=True)),
                ('fecha_calculo', models.DateTimeField(auto_now_add=True)),
                ('solicitud', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='estimacion', to='plataforma.solicitud')),
            ],
            options={
                'verbose_name': 'estimación',
                'verbose_name_plural': 'estimaciones',
            },
        ),
        migrations.CreateModel(
            name='Cotizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.PositiveIntegerField(verbose_name='monto final (CLP)')),
                ('plazo_dias', models.PositiveSmallIntegerField(verbose_name='plazo de entrega (días hábiles)')),
                ('validez_dias', models.PositiveSmallIntegerField(default=15, verbose_name='validez (días)')),
                ('detalle', models.TextField(verbose_name='alcance y condiciones')),
                ('fecha_emision', models.DateTimeField(default=django.utils.timezone.now)),
                ('respuesta_cliente', models.CharField(blank=True, choices=[('aceptada', 'Aceptada'), ('rechazada', 'Rechazada')], max_length=10)),
                ('comentario_cliente', models.TextField(blank=True)),
                ('fecha_respuesta', models.DateTimeField(blank=True, null=True)),
                ('emitida_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cotizaciones_emitidas', to=settings.AUTH_USER_MODEL)),
                ('solicitud', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cotizacion', to='plataforma.solicitud')),
            ],
            options={
                'verbose_name': 'cotización',
                'verbose_name_plural': 'cotizaciones',
            },
        ),
    ]
