# Generated by Django 5.0.6 on 2026-09-26 03:00

import django.db.models.deletion
import plataforma.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0002_datos_iniciales'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Adjunto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(max_length=255, upload_to=plataforma.models.ruta_adjunto)),
                ('nombre_original', models.CharField(max_length=255)),
                ('tamano', models.PositiveIntegerField(default=0)),
                ('tipo_contenido', models.CharField(blank=True, max_length=120)),
                ('es_equipo', models.BooleanField(default=False)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'archivo adjunto',
                'verbose_name_plural': 'archivos adjuntos',
                'ordering': ['-fecha', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='ConfiguracionSitio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correo_contacto', models.EmailField(default='contacto@axztra.cl', max_length=254, verbose_name='correo de contacto')),
                ('whatsapp', models.CharField(default='56912345678', help_text='Solo dígitos, con código de país. Ejemplo: 56912345678', max_length=20, verbose_name='número de WhatsApp')),
                ('whatsapp_visible', models.CharField(default='+56 9 1234 5678', max_length=30, verbose_name='WhatsApp como se muestra')),
                ('ubicacion', models.CharField(default='Hualpén, Región del Biobío, Chile', max_length=150, verbose_name='ubicación')),
                ('horario', models.CharField(default='Lunes a viernes, de 9:00 a 18:00 horas', max_length=150, verbose_name='horario de atención')),
                ('aviso', models.CharField(blank=True, help_text='Mensaje breve que se muestra sobre el menú del sitio. Déjalo vacío para ocultarlo.', max_length=200, verbose_name='aviso destacado')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'configuración del sitio',
                'verbose_name_plural': 'configuración del sitio',
            },
        ),
        migrations.CreateModel(
            name='MensajeSolicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('es_equipo', models.BooleanField(default=False)),
                ('texto', models.TextField()),
                ('leido', models.BooleanField(default=False)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'mensaje de solicitud',
                'verbose_name_plural': 'mensajes de solicitudes',
                'ordering': ['fecha', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='PreguntaFrecuente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pregunta', models.CharField(max_length=200)),
                ('respuesta', models.TextField()),
                ('palabras_clave', models.CharField(blank=True, help_text='Palabras separadas por coma que ayudan al asistente a encontrar esta respuesta.', max_length=300)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('activa', models.BooleanField(default=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'pregunta frecuente',
                'verbose_name_plural': 'preguntas frecuentes',
                'ordering': ['orden', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='RegistroActividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(choices=[('acceso', 'Acceso al panel'), ('estado', 'Cambio de estado'), ('cotizacion', 'Cotización emitida'), ('asignacion', 'Asignación de responsable'), ('gestion', 'Gestión interna'), ('mensaje', 'Mensaje al cliente'), ('adjunto', 'Archivo adjunto'), ('servicio', 'Catálogo de servicios'), ('contenido', 'Contenido del sitio'), ('exportacion', 'Exportación de datos'), ('cuenta', 'Cuenta de usuario')], max_length=20)),
                ('descripcion', models.CharField(max_length=300)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('fecha', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'registro de actividad',
                'verbose_name_plural': 'registro de actividad',
                'ordering': ['-fecha', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='TokenAPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('prefijo', models.CharField(db_index=True, editable=False, max_length=8)),
                ('token_hash', models.CharField(editable=False, max_length=64)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('ultimo_uso', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'token de integración',
                'verbose_name_plural': 'tokens de integración',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='items',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='version',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='perfilcliente',
            name='fecha_aceptacion_terminos',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='fecha_primera_respuesta',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='relacionada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='derivadas', to='plataforma.solicitud', verbose_name='solicitud relacionada'),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='responsable',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_staff': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_asignadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='token_envio',
            field=models.UUIDField(blank=True, editable=False, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='monto',
            field=models.PositiveIntegerField(verbose_name='monto neto (CLP)'),
        ),
        migrations.AddIndex(
            model_name='codigoverificacion',
            index=models.Index(fields=['usuario', 'usado'], name='codigo_usuario_usado'),
        ),
        migrations.AddIndex(
            model_name='mensajeasistente',
            index=models.Index(fields=['usuario', 'fecha'], name='asistente_usuario_fecha'),
        ),
        migrations.AddIndex(
            model_name='mensajeasistente',
            index=models.Index(fields=['es_asistente', 'fecha'], name='asistente_tipo_fecha'),
        ),
        migrations.AddIndex(
            model_name='solicitud',
            index=models.Index(fields=['estado', '-fecha_solicitud'], name='solicitud_estado_fecha'),
        ),
        migrations.AddIndex(
            model_name='solicitud',
            index=models.Index(fields=['cliente', '-fecha_solicitud'], name='solicitud_cliente_fecha'),
        ),
        migrations.AddIndex(
            model_name='solicitud',
            index=models.Index(fields=['responsable', 'estado'], name='solicitud_responsable'),
        ),
        migrations.AddIndex(
            model_name='solicitud',
            index=models.Index(fields=['tipo', '-fecha_solicitud'], name='solicitud_tipo_fecha'),
        ),
        migrations.AddIndex(
            model_name='solicitud',
            index=models.Index(fields=['prioridad', 'fecha_solicitud'], name='solicitud_prioridad'),
        ),
        migrations.AddField(
            model_name='adjunto',
            name='solicitud',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjuntos', to='plataforma.solicitud'),
        ),
        migrations.AddField(
            model_name='adjunto',
            name='subido_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adjuntos_subidos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mensajesolicitud',
            name='autor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mensajes_solicitud', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mensajesolicitud',
            name='solicitud',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes', to='plataforma.solicitud'),
        ),
        migrations.AddField(
            model_name='registroactividad',
            name='solicitud',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actividad', to='plataforma.solicitud'),
        ),
        migrations.AddField(
            model_name='registroactividad',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actividad', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tokenapi',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='mensajesolicitud',
            index=models.Index(fields=['solicitud', 'es_equipo', 'leido'], name='mensaje_no_leidos'),
        ),
    ]
