# Generated by Django 5.0.6 on 2026-09-30 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0002_datos_iniciales'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlataformaFormulario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solicitud_id', models.IntegerField()),
                ('tipo_servicio', models.CharField(max_length=100)),
                ('datos', models.JSONField(default=dict)),
                ('completado', models.BooleanField(default=False)),
                ('fecha_envio', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'plataforma_formulario',
            },
        ),
    ]
