# Generated by Django 5.0.6 on 2026-09-27 01:21

import django.db.models.deletion
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models
from django.db.models import Count
from django.db.models.functions import Lower

INDICE_CORREO = 'usuario_correo_unico'


def depurar_duplicados(apps, schema_editor):
    for nombre_modelo, campo in (('Servicio', 'nombre'), ('PreguntaFrecuente', 'pregunta')):
        modelo = apps.get_model('plataforma', nombre_modelo)
        repetidos = (
            modelo.objects.annotate(clave=Lower(campo)).values('clave')
            .annotate(total=Count('pk')).filter(total__gt=1).values_list('clave', flat=True)
        )
        for clave in list(repetidos):
            copias = modelo.objects.annotate(clave=Lower(campo)).filter(clave=clave).order_by('pk')
            for numero, objeto in enumerate(copias[1:], start=2):
                valor = f'{getattr(objeto, campo)} ({numero})'
                modelo.objects.filter(pk=objeto.pk).update(**{campo: valor})


def crear_indice_correo(apps, schema_editor):
    usuario = apps.get_model(settings.AUTH_USER_MODEL)
    repetidos = (
        usuario.objects.exclude(email='').annotate(clave=Lower('email')).values('clave')
        .annotate(total=Count('pk')).filter(total__gt=1)
    )
    if repetidos.exists():
        return
    tabla = schema_editor.quote_name(usuario._meta.db_table)
    columna = schema_editor.quote_name('email')
    schema_editor.execute(
        f"CREATE UNIQUE INDEX IF NOT EXISTS {INDICE_CORREO} ON {tabla} (lower({columna})) WHERE {columna} <> ''"
    )


def eliminar_indice_correo(apps, schema_editor):
    schema_editor.execute(f'DROP INDEX IF EXISTS {INDICE_CORREO}')


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0004_contenido_inicial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(depurar_duplicados, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='solicitud',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitudes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='historialsolicitud',
            index=models.Index(fields=['solicitud', '-fecha'], name='historial_solicitud_fecha'),
        ),
        migrations.AddIndex(
            model_name='mensajesolicitud',
            index=models.Index(fields=['es_equipo', 'leido'], name='mensaje_pendientes'),
        ),
        migrations.AddIndex(
            model_name='registroactividad',
            index=models.Index(fields=['accion', '-fecha'], name='actividad_accion_fecha'),
        ),
        migrations.AddIndex(
            model_name='solicitud',
            index=models.Index(fields=['estado', '-fecha_actualizacion'], name='solicitud_estado_actualizada'),
        ),
        migrations.AddConstraint(
            model_name='configuracionsitio',
            constraint=models.CheckConstraint(check=models.Q(('pk', 1)), name='configuracion_registro_unico'),
        ),
        migrations.AddConstraint(
            model_name='cotizacion',
            constraint=models.CheckConstraint(check=models.Q(('plazo_dias__gte', 1)), name='cotizacion_plazo_positivo'),
        ),
        migrations.AddConstraint(
            model_name='cotizacion',
            constraint=models.CheckConstraint(check=models.Q(('validez_dias__gte', 1)), name='cotizacion_validez_positiva'),
        ),
        migrations.AddConstraint(
            model_name='cotizacion',
            constraint=models.CheckConstraint(check=models.Q(('version__gte', 1)), name='cotizacion_version_positiva'),
        ),
        migrations.AddConstraint(
            model_name='cotizacion',
            constraint=models.CheckConstraint(check=models.Q(('respuesta_cliente__in', ['', 'aceptada', 'rechazada'])), name='cotizacion_respuesta_valida'),
        ),
        migrations.AddConstraint(
            model_name='estimacion',
            constraint=models.CheckConstraint(check=models.Q(('monto_minimo__lte', models.F('monto_maximo'))), name='estimacion_rango_valido'),
        ),
        migrations.AddConstraint(
            model_name='estimacion',
            constraint=models.CheckConstraint(check=models.Q(('semanas_minimas__lte', models.F('semanas_maximas'))), name='estimacion_plazo_valido'),
        ),
        migrations.AddConstraint(
            model_name='mensajesolicitud',
            constraint=models.CheckConstraint(check=models.Q(('texto', ''), _negated=True), name='mensaje_con_texto'),
        ),
        migrations.AddConstraint(
            model_name='preguntafrecuente',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('pregunta'), name='pregunta_frecuente_unica'),
        ),
        migrations.AddConstraint(
            model_name='requerimientoweb',
            constraint=models.CheckConstraint(check=models.Q(('num_paginas__gte', 1), ('num_paginas__lte', 60)), name='requerimiento_paginas_rango'),
        ),
        migrations.AddConstraint(
            model_name='requerimientoweb',
            constraint=models.CheckConstraint(check=models.Q(('complejidad__in', ['basica', 'media', 'alta'])), name='requerimiento_complejidad_valida'),
        ),
        migrations.AddConstraint(
            model_name='requerimientoweb',
            constraint=models.CheckConstraint(check=models.Q(('tipo_sitio__in', ['landing', 'corporativo', 'portafolio', 'servicios', 'tienda'])), name='requerimiento_tipo_sitio_valido'),
        ),
        migrations.AddConstraint(
            model_name='servicio',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('nombre'), name='servicio_nombre_unico'),
        ),
        migrations.AddConstraint(
            model_name='servicio',
            constraint=models.CheckConstraint(check=models.Q(('tipo__in', ['Creacion', 'Mejora', 'Soporte', 'Mantenimiento'])), name='servicio_tipo_valido'),
        ),
        migrations.AddConstraint(
            model_name='solicitud',
            constraint=models.CheckConstraint(check=models.Q(('prioridad__in', ['baja', 'media', 'alta', 'urgente'])), name='solicitud_prioridad_valida'),
        ),
        migrations.AddConstraint(
            model_name='solicitud',
            constraint=models.CheckConstraint(check=models.Q(('tipo__in', ['Creacion', 'Mejora', 'Soporte', 'Mantenimiento'])), name='solicitud_tipo_valido'),
        ),
        migrations.RunPython(crear_indice_correo, eliminar_indice_correo),
    ]
