# Generated by Django 5.0.6 on 2026-10-01 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0005_integridad_datos'),
    ]

    operations = [
        migrations.AddField(
            model_name='requerimientoweb',
            name='colores',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='requerimientoweb',
            name='dominio',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='requerimientoweb',
            name='estilo_visual',
            field=models.CharField(choices=[('sin_preferencia', 'Sin preferencia'), ('moderno', 'Moderno'), ('minimalista', 'Minimalista'), ('elegante', 'Elegante'), ('colorido', 'Colorido'), ('corporativo', 'Formal o corporativo')], default='sin_preferencia', max_length=20),
        ),
        migrations.AddField(
            model_name='requerimientoweb',
            name='medio_contacto',
            field=models.CharField(choices=[('correo', 'Correo electrónico'), ('telefono', 'Llamada telefónica'), ('whatsapp', 'WhatsApp')], default='correo', max_length=10),
        ),
        migrations.AddField(
            model_name='requerimientoweb',
            name='presupuesto',
            field=models.CharField(choices=[('por_definir', 'Aún no lo defino'), ('menos_300', 'Menos de $300.000'), ('300_600', 'Entre $300.000 y $600.000'), ('600_1000', 'Entre $600.000 y $1.000.000'), ('mas_1000', 'Más de $1.000.000')], default='por_definir', max_length=12),
        ),
        migrations.AddField(
            model_name='requerimientoweb',
            name='secciones',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='requerimientoweb',
            name='sitios_referencia',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='requerimientoweb',
            name='situacion_logo',
            field=models.CharField(choices=[('tiene', 'Ya tengo logo'), ('mejorar', 'Tengo logo, pero quiero mejorarlo'), ('crear', 'Necesito un logo nuevo')], default='tiene', max_length=10),
        ),
        migrations.AddConstraint(
            model_name='requerimientoweb',
            constraint=models.CheckConstraint(check=models.Q(('estilo_visual__in', ['sin_preferencia', 'moderno', 'minimalista', 'elegante', 'colorido', 'corporativo'])), name='requerimiento_estilo_valido'),
        ),
        migrations.AddConstraint(
            model_name='requerimientoweb',
            constraint=models.CheckConstraint(check=models.Q(('situacion_logo__in', ['tiene', 'mejorar', 'crear'])), name='requerimiento_logo_valido'),
        ),
        migrations.AddConstraint(
            model_name='requerimientoweb',
            constraint=models.CheckConstraint(check=models.Q(('presupuesto__in', ['por_definir', 'menos_300', '300_600', '600_1000', 'mas_1000'])), name='requerimiento_presupuesto_valido'),
        ),
        migrations.AddConstraint(
            model_name='requerimientoweb',
            constraint=models.CheckConstraint(check=models.Q(('medio_contacto__in', ['correo', 'telefono', 'whatsapp'])), name='requerimiento_contacto_valido'),
        ),
    ]
